from typing import Dict, List

intent_questions: Dict[str, List[str]] = {
    "Restaurant": [
        "Are you talking about restaurants?",
        "Are you talking about food?",
        "Are you talking about eat?",
        "Are you talking about cook?",
        "Is the user talking about restaurants?",
        "Is the user talking about food?",
        "Is the user talking about eat?",
        "Is the user talking about cook?",
    ],
    "Hotel": [
        "Are you talking about hotels?",
        "Are you talking about room?",
        "Are you talking about travel?",
        "Are you talking about service?",
        "Are you talking about sleep?",
        "Are you talking about journey?",
        "Is the user talking about hotels?",
        "Is the user talking about room?",
        "Is the user talking about travel?",
        "Is the user talking about service?",
        "Is the user talking about bed?",
        "Is the user talking about journey?",
    ],
    "Movie": [
        "Are you talking about movies?",
        "Are you talking about cartoon?",
        "Are you talking about poster?",
        "Are you talking about story?",
        "Are you talking about theaters?",
        "Are you talking about ticket?",
        "Is the user talking about movies?",
        "Is the user talking about cartoon?",
        "Is the user talking about poster?",
        "Is the user talking about story?",
        "Is the user talking about theaters?",
        "Is the user talking about ticket?",
    ],
    "Song": [
        "Are you talking about songs?",
        "Are you talking about instrumental?",
        "Are you talking about album?",
        "Are you talking about band?",
        "Are you talking about music?",
        "Is the user talking about songs?",
        "Is the user talking about instrumental?",
        "Is the user talking about album?",
        "Is the user talking about band?",
        "Is the user talking about music?",
    ],
    "Transportation": [
        "Are you talking about transportation?",
        "Are you talking about vehicle?",
        "Are you talking about trip?",
        "Are you talking about traffic?",
        "Are you talking about destination?",
        "Are you talking about journey?",
        "Are you talking about ticket?",
        "Is the user talking about transportation?",
        "Is the user talking about vehicle?",
        "Is the user talking about trip?",
        "Is the user talking about traffic?",
        "Is the user talking about destination?",
        "Is the user talking about journey?",
        "Is the user talking about ticket?",
    ],
    "Attraction": [
        "Are you talking about country?",
        "Are you talking about landscape?",
        "Are you talking about adventure?",
        "Are you talking about vacation?",
        "Are you talking about holiday?",
        "Are you talking about journey?",
        "Is the user talking about country?",
        "Is the user talking about landscape?",
        "Is the user talking about adventure?",
        "Is the user talking about vacation?",
        "Is the user talking about holiday?",
        "Is the user talking about journey?",
    ],
}



